### PR TITLE
Ability to specify network interface

### PR DESCRIPTION
**Pull request by bottleneko**
Current code can't work with distributed Erlang on internal interface

### CODE REVIEW

**Comment by erlanger** [comment]
Thanks for the PR, looks good, only one change I would like you to make before merge:

* leave `start_link/2` and `start_link/3` with default arguments

I'll merge after that change.
Thanks!

**Comment by bottleneko** [comment]
Thanks for your answer! Sorry that i forget about backward compatibility. I've push commit with start_link/2,3 and logic for reproduce current behavior.

**Comment by erlanger** [comment]
Thanks! Merged.

**Comment by erlanger** [comment]
Hi @bottleneko,

   Just had to revert the PR because `./tests/test-nodefinder` is failing. Could you post a PR making sure the tests pass?
Thanks!

**Pull request merged**
